### ISSUE TITLE
[NGAP] DialSCTPExt not returning

### ISSUE THREAD

**Issue by brodeuralexis** [my5G/my5G-RANTester#54]
I'm currently trying to setup an Open5GS sandbox for research purposes.  I'm new to 5G networks in general and trying to setup my own to better understand 3GPP.

For my Open5GS environment, I've directly used the code from https://github.com/herlesupreeth/docker_open5gs instead for a 5G SA deployment as I've had problems to get my5G's version to work (still trying to debug it).

The docker containers I currently have on my host are the following:
```
CONTAINER ID   IMAGE            COMMAND                  CREATED          STATUS          PORTS                                                                                                  NAMES
66e44a698450   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   0.0.0.0:2152->2152/udp, :::2152->2152/udp, 8805/udp, 9091/tcp                                          upf
890abaa7639e   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   2123/udp, 3868/sctp, 3868/tcp, 3868/udp, 5868/tcp, 5868/udp, 7777/tcp, 8805/udp, 5868/sctp, 9091/tcp   smf
1fe52bdbe26f   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp, 9091/tcp, 0.0.0.0:38412->38412/sctp, :::38412->38412/sctp                                    amf
91f8e59094ba   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp                                                                                               udm
84031730d027   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp                                                                                               ausf
b1ce722a4468   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp, 9091/tcp                                                                                     pcf
9ee9636339e4   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp                                                                                               nssf
3ab2a1b07bda   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp                                                                                               bsf
1441355c773a   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp                                                                                               udr
e7e42b887962   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                              webui
0518e97c0b5c   mongo:6.0        "docker-entrypoint.s…"   36 minutes ago   Up 36 minutes   27017/tcp, 27017/udp                                                                                   mongo
26bc9de13b8a   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp                                                                                               nrf
077e8522e008   docker_open5gs   "/bin/sh -c /open5gs…"   36 minutes ago   Up 36 minutes   7777/tcp                                                                                               scp
7290d0790292   docker_metrics   "/bin/sh -c /mnt/met…"   36 minutes ago   Up 36 minutes   0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                                                              metrics
```

My *config.yaml* looks like the following:

```yaml
gnodeb:
  controlif:
    ip: "127.0.0.1"
    port: 9487
  dataif:
    ip: "127.0.0.1"
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "95"
    tac: "000001"
    gnbid: "000003"
  slicesupportlist:
    sst: "01"
    sd: "000001"
ue:
  msin: "0000000043"
  key: "0C0A34601D4F07677303652C0462535B"
  opc: "63bfa50ee6523365ff14c1f45f88737d"
  amf: "8000"
  sqn: "0000000"
  dnn: "default"
  hplmn:
    mcc: "208"
    mnc: "95"
  snssai:
    sst: 1
    sd: "000001"
  integrity:
    nia0: false
    nia1: false
    nia2: true
  ciphering:
    nea0: true
    nea1: false
    nea2: false
  test: "test-5g-guti"
amfif:
  ip: "127.0.0.1"
  port: 38412
logs:
    level: 4
```

Adding my own logging around DialSCTPExt (before and after), and running the gNB, I get the following:

```
my5G-RANTester git:(master) $ go run ./cmd/app.go gnb
INFO[0000] my5G-RANTester version 1.0.1                 
INFO[0000] ---------------------------------------      
INFO[0000] [TESTER] Starting test function: Testing an gnb attached with configuration 
INFO[0000] [TESTER][GNB] Number of GNBs: 1              
INFO[0000] [TESTER][GNB] Control interface IP/Port: 127.0.0.1/9487 
INFO[0000] [TESTER][GNB] Data interface IP/Port: 127.0.0.1/2152 
INFO[0000] [TESTER][AMF] AMF IP/Port: 127.0.0.1/38412   
INFO[0000] ---------------------------------------      
INFO[0000] Before DialSCTPExt: loc=127.0.0.1:9487 rem=127.0.0.1:38412
```

For the AMF, the port is forwarded (`:::38412->38412/sctp`), but nothing is for the Control Interface Port.
Now I am stuck trying to understand what is supposed to listen on port 9487.
